# Generated by Django 2.2.3 on 2019-07-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default='Note', on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
    ]
